@startuml
' @layout_type Sugiyama
W --> R
C --> Q
O --> A
V --> N
N --> V
S --> AC
AB --> AA
G --> C
W --> J
E --> B
B --> Q
N --> AF
Q --> AB
E --> S
G --> I
AC --> X
U --> F
F --> Y
D --> Y
AF --> N
B --> AB
AA --> AD
Y --> K
Q --> E
X --> Q
O --> E
W --> A
X --> V
W --> Y
T --> Y
Q --> V
Q --> B
AC --> I
R --> AB
C --> E
A --> AA
X --> A
P --> Q
T --> AA
O --> U
O --> J
P --> O
@enduml
