cc_library(
    name = "activity_type_enum",
    hdrs = ["activity_type_enum.hpp"],
    copts = ["-std=c++17"],
    features = ["c++17"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "line_head_enum",
    hdrs = ["line_head_enum.hpp"],
    copts = ["-std=c++17"],
    features = ["c++17"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "line_type_enum",
    hdrs = ["line_type_enum.hpp"],
    copts = ["-std=c++17"],
    features = ["c++17"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "node_type_enum",
    hdrs = ["node_type_enum.hpp"],
    copts = ["-std=c++17"],
    features = ["c++17"],
    visibility = ["//visibility:public"],
)
