
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[304] =
    {   0,
        0,    0,    0,    0,   66,   64,   63,   63,   64,   37,
       50,   48,   49,   35,   39,   32,   41,   33,   42,   43,
       64,   60,   60,   60,   60,   60,   44,   45,   40,   60,
       60,   60,   60,   60,   60,   36,   60,   60,   38,   46,
       34,   47,   63,   37,   39,   41,   60,   64,   29,   28,
       28,   29,   63,    0,   61,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,   60,   60,   60,   60,   23,
        0,    0,    0,    0,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   63,    0,    0,    0,   31,
       60,   28,    0,   62,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   60,   60,   60,    0,    0,
        0,    0,    0,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,    0,    0,   30,   31,
       60,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,   24,   60,    0,    0,    0,
        0,    0,   60,   60,   60,   60,   60,   60,   10,   60,
       60,   60,   60,   60,   60,    0,   26,    0,    0,    0,
       58,    0,    0,    0,    0,    0,    0,    0,    0,   25,
        0,    0,    0,    0,    0,   60,   60,   60,    3,   60,
       60,   60,   60,   60,   60,   60,   60,   26,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,   60,   60,    7,   60,    9,   60,   60,   60,
       60,   60,   16,    0,    0,    0,    2,    0,    0,    0,
        0,    0,    0,    0,    0,   21,   60,   60,    8,   60,
       60,   60,   60,   60,    0,    0,    0,    0,    0,    0,
        0,    0,   19,   18,   17,    4,   60,   60,   60,   60,
       14,   60,   27,    0,    0,    0,   51,    0,    0,    1,
        0,   60,   11,   12,   13,   60,    0,   57,    0,    0,
        0,    0,    0,    6,   15,    0,    0,    0,    0,   53,
        0,    0,   56,    0,   54,    0,   55,    0,    0,    0,

        5,   52,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    8,    9,
       10,   11,   12,   13,   14,   15,    1,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,   18,
        1,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   24,   24,   31,   24,   32,   33,   34,
       24,   35,   36,   37,   38,   24,   39,   24,   24,   24,
       40,    1,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   24,   53,   54,   55,   56,
       57,   58,   24,   59,   60,   61,   62,   24,   63,   64,
       65,   24,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    3,    4,    2,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[310] =
    {   0,
        0,   68,   69,   81,  646,  647,   74,   85,  639,  647,
      647,   87,  647,  647,  647,  647,  647,  647,  647,  647,
       50,  641,   78,   88,   75,   82,   96,  647,  647,   93,
       90,  106,   96,  103,  109,  640,   91,  110,  639,  647,
      647,  647,  162,  113,  118,  126,  123,  143,  647,  170,
      176,   90,  180,  635,  637,  182,  117,  623,  186,  586,
      106,  593,  579,  142,  647,  632,  165,  163,  158,  631,
      156,  183,  125,  139,  189,  203,  148,  206,  207,  208,
      211,  212,  214,  217,  218,  230,  217,  190,  224,  299,
      221,  236,  205,  647,  251,  241,  274,  589,  582,  584,

      565,  569,  576,  573,  582,  231,  258,  242,  194,  200,
      231,  247,  259,  262,  252,  275,  277,  280,  281,  288,
      282,  294,  305,  293,  312,  295,  285,  622,  647,  371,
      321,  323,  346,  311,  608,  348,  573,  574,  559,  563,
      567,  560,  565,  557,  612,  611,  333,  309,  330,  294,
      350,  350,  341,  326,  342,  335,  349,  388,  610,  390,
      395,  396,  398,  402,  400,  378,  609,  412,  405,  414,
      647,  552,  567,  554,  546,  546,  563,  544,  543,  600,
      561,  382,  383,  397,  395,  415,  417,  419,  598,  422,
      425,  426,  430,  429,  431,  432,  433,  647,  408,  556,

      538,  544,  536,  544,  541,  551,  531,  647,  422,  427,
      424,  551,  440,  450,  588,  454,  587,  455,  459,  460,
      457,  461,  586,  434,  533,  522,  647,  543,  528,  540,
      535,  527,  540,  539,  538,  647,  463,  467,  574,  469,
      470,  472,  473,  478,  458,  529,  509,  505,  507,  483,
      500,  492,  647,  647,  647,  488,  479,  482,  485,  489,
      542,  493,  647,  481,  493,  475,  496,  480,  485,  647,
      488,  494,  528,  527,  526,  496,  463,  647,  467,  474,
      459,  472,  464,  514,  512,  455,  464,  458,  448,  647,
      464,  457,  647,  438,  647,  440,  647,  450,  272,   87,

      647,  647,  647,  551,  556,  559,  563,  568,  573
    } ;

static const flex_int16_t yy_def[310] =
    {   0,
      303,    1,  304,  304,  303,  303,  303,  303,  305,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  306,  306,  306,  306,  306,  303,  303,  303,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  303,
      303,  303,  303,  307,  307,  307,  306,  307,  303,  303,
      303,  303,  303,  305,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  306,  306,  306,  306,  306,
      303,  303,  303,  303,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  303,  307,  303,  307,  308,
      306,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  306,  306,  306,  303,  303,
      303,  303,  303,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  303,  309,  303,  308,
      306,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  306,  306,  306,  303,  303,  303,
      303,  303,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  303,  306,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  306,
      303,  303,  303,  303,  303,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  306,  306,  306,  306,
      306,  306,  306,  306,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  306,  306,  306,  306,  306,
      306,  306,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  306,  306,  306,  306,  306,  303,  303,  303,  303,
      303,  303,  303,  306,  306,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,    0,  303,  303,  303,  303,  303,  303
    } ;

static const flex_int16_t yy_nxt[717] =
    {   0,
        6,    7,    8,    6,    7,    9,   10,   11,   12,   13,
       14,   15,   16,   17,    6,    6,   18,   19,   20,    6,
       21,   22,   22,   22,   23,   22,   22,   22,   22,   22,
       24,   22,   22,   22,   25,   22,   22,   26,   22,   27,
       28,   29,   22,   30,   22,   31,   32,   33,   22,   22,
       22,   34,   22,   24,   35,   22,   36,   37,   25,   38,
       22,   26,   22,   39,   22,   40,   41,   42,    6,   43,
       50,   51,   43,   50,   44,   53,   53,   65,   53,   45,
       65,   46,   50,   51,   65,   50,   53,   53,   56,   53,
       65,   56,   65,   65,   52,   65,   60,   61,   65,   47,

       57,   58,   59,   62,   69,   65,   52,   63,   65,   64,
       67,   65,   65,   68,   89,   70,   52,   89,   71,   89,
       72,   93,   89,   47,   73,   65,   69,   89,   52,   74,
       89,   58,   59,  302,   67,   68,   48,   75,   67,   70,
       71,   77,   72,   78,   89,   93,   73,   89,   76,   84,
       65,   80,   99,   74,  112,   91,   83,   79,   82,   81,
       65,  100,   67,   86,   53,   65,   86,   65,   87,  113,
       85,   92,   92,   87,   92,   87,  112,   92,   92,   91,
       92,   53,   53,   56,   53,  108,   56,   96,  109,  107,
       96,   65,  113,   88,  103,   57,   58,   59,   97,  104,

       58,   59,  105,  106,  110,   65,  116,  108,   65,   65,
       65,  107,  109,   65,   65,  111,   65,   88,   89,   65,
       65,   89,  127,   65,  148,   89,  110,  106,   89,  132,
       87,   86,   53,   65,   86,  149,   87,   92,   92,  111,
       92,   87,   96,   87,   65,   96,  127,  148,  114,  117,
      118,  132,   96,   97,   65,   96,  121,  131,  115,  149,
       65,   88,  145,   97,   65,  125,   95,  150,  119,  120,
      147,  151,  122,  124,  123,  133,  126,   65,  133,   65,
      152,  131,   65,   65,   65,   88,  145,  134,  135,  136,
       65,  150,  147,  151,  146,   65,   65,   65,   87,  128,

      128,  129,  152,  128,  128,  128,  128,   65,  154,  128,
      128,  128,  128,  128,   65,  128,  128,  128,  146,  128,
      155,  166,  153,   65,  168,  135,  136,  168,   65,  160,
      183,  301,  158,  181,  157,   65,  156,   65,  128,  128,
      128,  161,  159,   65,   65,  166,  167,  133,  162,  170,
      133,   65,  170,  163,  183,  181,  165,  171,  182,  134,
      135,  136,  135,  136,  128,  128,  128,  128,  167,  180,
      164,  128,  128,  129,  184,  128,  128,  128,  128,  185,
      182,  128,  128,  128,  128,  128,  187,  128,  128,  128,
       65,  128,   65,  180,  189,  188,  184,   65,   65,  186,

       65,  185,   65,  198,   65,  190,  170,  209,  210,  170,
      128,  128,  128,  168,  171,  170,  168,   65,  170,   65,
      169,   65,  211,  171,   65,  198,  212,   65,   65,  209,
      210,   65,   65,   65,   65,   65,  128,  128,  128,  128,
      224,  194,   65,  199,  211,  197,  233,  192,  191,  196,
      212,  234,   65,  193,  195,  235,   65,   65,  213,   65,
      214,   65,   65,   65,  224,   65,  215,  199,  233,   65,
      245,   65,   65,  234,   65,   65,  221,  216,  219,  235,
       65,   65,  220,  263,   65,  237,  218,   65,  222,  217,
       65,   65,  271,  223,  245,   65,   65,  300,   65,  299,

      239,  298,  241,  242,  297,  263,  240,  296,  295,  294,
      238,  293,  292,  243,   65,  259,   65,  291,  257,  290,
      289,  244,  288,  256,  287,  258,  261,  286,   65,   65,
       65,  260,  274,  283,  282,  272,  281,  273,  280,  279,
      278,  277,  262,  285,   65,  270,  269,  268,  275,  284,
      276,   49,   49,   49,   49,   49,   54,   54,   54,   54,
       54,   66,  267,   66,   90,  266,  265,   90,  130,  130,
      130,  264,  130,  128,  128,  128,   65,  128,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,   65,   65,
       65,  236,  232,  231,  230,  229,  228,  227,  226,  225,

       65,  208,   65,  207,  206,  205,  204,  203,  202,  201,
      200,   65,   65,   65,   65,  179,  178,  177,  176,  175,
      174,  173,  172,  169,  129,  144,  143,  142,  141,  140,
      139,  138,  137,   65,   65,  102,  101,   98,   95,   94,
       55,   65,   65,   65,   55,  303,    5,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303
    } ;

static const flex_int16_t yy_chk[717] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    3,    2,    3,    2,    7,    7,   25,    7,    2,
       23,    2,    4,    4,   26,    4,    8,    8,   12,    8,
       24,   12,   31,   37,    3,   30,   21,   21,   33,    2,

       12,   12,   12,   21,   25,   34,    4,   21,   32,   21,
       23,   35,   38,   24,   44,   26,    3,   44,   27,   45,
       27,   52,   45,    2,   27,   47,   25,   46,    4,   27,
       46,   57,   57,  300,   23,   24,    2,   30,   32,   26,
       27,   31,   27,   31,   48,   52,   27,   48,   30,   37,
       77,   33,   61,   27,   73,   47,   35,   32,   34,   33,
       69,   61,   32,   43,   43,   68,   43,   67,   43,   74,
       38,   50,   50,   43,   50,   43,   73,   51,   51,   47,
       51,   53,   53,   56,   53,   69,   56,   59,   71,   68,
       59,   75,   74,   43,   64,   56,   56,   56,   59,   64,

       59,   59,   64,   67,   72,   76,   77,   69,   78,   79,
       80,   68,   71,   81,   82,   72,   83,   43,   87,   84,
       85,   87,   88,   91,  109,   89,   72,   67,   89,   93,
       43,   86,   86,  106,   86,  110,   86,   92,   92,   72,
       92,   86,   96,   86,  108,   96,   88,  109,   75,   78,
       79,   93,   95,   96,  115,   95,   81,   91,   76,  110,
      107,   86,  106,   95,  114,   85,   95,  111,   80,   80,
      108,  112,   82,   84,   83,   97,   85,  116,   97,  117,
      113,   91,  118,  119,  121,   86,  106,   97,   97,   97,
      120,  111,  108,  112,  107,  124,  122,  126,   86,   90,

       90,   90,  113,   90,   90,   90,   90,  123,  115,   90,
       90,   90,   90,   90,  125,   90,   90,   90,  107,   90,
      116,  127,  114,  131,  132,  134,  134,  132,  154,  121,
      150,  299,  119,  148,  118,  147,  117,  156,   90,   90,
       90,  122,  120,  153,  155,  127,  131,  133,  123,  136,
      133,  157,  136,  124,  150,  148,  126,  136,  149,  133,
      133,  133,  136,  136,   90,   90,   90,   90,  131,  147,
      125,  130,  130,  130,  151,  130,  130,  130,  130,  152,
      149,  130,  130,  130,  130,  130,  154,  130,  130,  130,
      158,  130,  160,  147,  156,  155,  151,  161,  162,  153,

      163,  152,  165,  166,  164,  157,  169,  182,  183,  169,
      130,  130,  130,  168,  169,  170,  168,  186,  170,  187,
      169,  188,  184,  170,  190,  166,  185,  191,  192,  182,
      183,  194,  193,  195,  196,  197,  130,  130,  130,  130,
      199,  162,  213,  168,  184,  165,  209,  160,  158,  164,
      185,  210,  214,  161,  163,  211,  216,  218,  186,  221,
      187,  219,  220,  222,  199,  237,  188,  168,  209,  238,
      224,  240,  241,  210,  242,  243,  195,  190,  193,  211,
      244,  257,  194,  245,  258,  213,  192,  259,  196,  191,
      256,  260,  256,  197,  224,  262,  272,  298,  276,  296,

      216,  294,  219,  220,  292,  245,  218,  291,  289,  288,
      214,  287,  286,  221,  285,  241,  284,  283,  238,  282,
      281,  222,  280,  237,  279,  240,  243,  277,  275,  274,
      273,  242,  259,  271,  269,  257,  268,  258,  267,  266,
      265,  264,  244,  276,  261,  252,  251,  250,  260,  272,
      262,  304,  304,  304,  304,  304,  305,  305,  305,  305,
      305,  306,  249,  306,  307,  248,  247,  307,  308,  308,
      308,  246,  308,  309,  309,  309,  239,  309,  235,  234,
      233,  232,  231,  230,  229,  228,  226,  225,  223,  217,
      215,  212,  207,  206,  205,  204,  203,  202,  201,  200,

      189,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  167,  159,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  135,  128,  105,  104,  103,  102,  101,
      100,   99,   98,   70,   66,   63,   62,   60,   58,   55,
       54,   39,   36,   22,    9,    5,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include "parser.tab.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

extern void yyrestart(FILE *input_file);
extern void yy_switch_to_buffer(void* buffer);
#line 710 "lex.yy.c"

#line 712 "lex.yy.c"

#define INITIAL 0
#define NOTE_STATE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif



#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif


/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 13 "lexer.l"


#line 936 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 304 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 647 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "lexer.l"
{ printf("TOKEN: STARTUML (%s)\n", yytext); return STARTUML; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "lexer.l"
{ printf("TOKEN: END_UML (%s)\n", yytext); return END_UML; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "lexer.l"
{ printf("TOKEN: CLASS\n"); return CLASS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "lexer.l"
{ printf("TOKEN: ABSTRACT\n"); return ABSTRACT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "lexer.l"
{ printf("TOKEN: ABSTRACT_CLASS\n"); return ABSTRACT_CLASS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "lexer.l"
{ printf("TOKEN: ANNOTATION\n"); return ANNOTATION; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "lexer.l"
{ printf("TOKEN: CIRCLE\n"); return CIRCLE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "lexer.l"
{ printf("TOKEN: DIAMOND\n"); return DIAMOND; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "lexer.l"
{ printf("TOKEN: ENTITY\n"); return ENTITY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "lexer.l"
{ printf("TOKEN: ENUM\n"); return ENUM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "lexer.l"
{ printf("TOKEN: EXCEPTION\n"); return EXCEPTION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "lexer.l"
{ printf("TOKEN: INTERFACE\n"); return INTERFACE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "lexer.l"
{ printf("TOKEN: METACLASS\n"); return METACLASS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "lexer.l"
{ printf("TOKEN: PROTOCOL\n"); return PROTOCOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "lexer.l"
{ printf("TOKEN: STEREOTYPE\n"); return STEREOTYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "lexer.l"
{ printf("TOKEN: STRUCT\n"); return STRUCT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "lexer.l"
{ printf("TOKEN: DOWN recognized\n"); return DOWN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "lexer.l"
{ printf("TOKEN: UP recognized\n"); return UP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "lexer.l"
{ printf("TOKEN: LEFT recognized\n"); return LEFT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "lexer.l"
{ printf("TOKEN: RIGHT recognized\n"); return RIGHT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "lexer.l"
{ BEGIN(NOTE_STATE); printf("START NOTE\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lexer.l"
{ BEGIN(INITIAL); printf("END NOTE\n"); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 43 "lexer.l"
{ /* ignoruj białe znaki wewnątrz */ }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lexer.l"
{ /* ignoruj każdy inny znak wewnątrz */ }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 46 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: ATTRIBUTE (%s)\n", yytext); return ATTRIBUTE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 47 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: START_IDENTIFIER (%s)\n", yytext); return START_IDENTIFIER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "lexer.l"
{ printf("TOKEN: COMMA\n"); return COMMA; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "lexer.l"
{ printf("TOKEN: COLON\n"); return COLON; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "lexer.l"
{ printf("TOKEN: PIPE\n"); return PIPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "lexer.l"
{ printf("TOKEN: STAR\n"); return STAR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("TOKEN: O\n"); return O; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "lexer.l"
{ printf("TOKEN: HASH\n"); return HASH; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("TOKEN: X\n"); return X; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("TOKEN: PLUS\n"); return PLUS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("TOKEN: HAT\n"); return HAT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("TOKEN: HYPHEN\n"); return HYPHEN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("TOKEN: L_ANGLE_BRACE\n"); return L_ANGLE_BRACE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("TOKEN: R_ANGLE_BRACE\n"); return R_ANGLE_BRACE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("TOKEN: L_SQUARE_BRACE\n"); return L_SQUARE_BRACE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("TOKEN: R_SQUARE_BRACE\n"); return R_SQUARE_BRACE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("TOKEN: L_CURLY_BRACE\n"); return L_CURLY_BRACE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("TOKEN: R_CURLY_BRACE\n"); return R_CURLY_BRACE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("TOKEN: LBRACE\n"); return LBRACE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("TOKEN: RBRACE\n"); return RBRACE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("TOKEN: QUOTE\n"); return QUOTE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("TOKEN: AT_POSITION\n"); return AT_POSITION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("TOKEN: AT_POSITION_FIXED\n"); return AT_POSITION_FIXED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("TOKEN: SPLIT_EDGE\n"); return SPLIT_EDGE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("TOKEN: SKIP_LAYOUT\n"); return SKIP_LAYOUT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("TOKEN: DIAGRAM_TYPE\n"); return DIAGRAM_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("TOKEN: LAYOUT_TYPE\n"); return LAYOUT_TYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("TOKEN: EDGE_TYPE\n"); return EDGE_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 77 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: POSITION_ARGS (%s)\n", yytext); return POSITION_ARGS; }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 79 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: LINE_LAST_IDENTIFIER (%s)\n", yytext); return LINE_LAST_IDENTIFIER; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: IDENTIFIER (%s)\n", yytext); return IDENTIFIER; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 81 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: QUOTED_ID (%s)\n", yytext); return IDENTIFIER; }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 82 "lexer.l"
{ yylval.str = strdup(yytext); printf("TOKEN: QUOTED_ID (%s)\n", yytext); return LINE_LAST_IDENTIFIER; }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 84 "lexer.l"
{ /* Debugging whitespace is usually too noisy, but you can add it if needed: printf("WS\n"); */ }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("UNKNOWN CHARACTER: *%s*\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "lexer.l"
ECHO;
	YY_BREAK
#line 1325 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NOTE_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;

	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 304 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 304 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 303);

		return yy_is_jam ? 0 : yy_current_state;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;

	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{

	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno  (void)
{

    return yylineno;
}

/** Get the input stream.
 *
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 *
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 *
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 *
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno (int  _line_number )
{

    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 87 "lexer.l"



int yywrap() {
    return 1;
}

void yy_switch_to_buffer(void* buffer) {
    // Flex expects FILE*, so you need to adapt here
    yyrestart((FILE*)buffer);
}
